include: "rules/common.smk"
include: "rules/acquire_anat.smk"
include: "rules/acquire_func.smk"
include: "rules/mot_correct.smk"
include: "rules/tmean.smk"
include: "rules/coreg.smk"
include: "rules/figure.smk"

wildcard_constraints:
    task="|".join(TASKS)

rule all:
    input:
        rules.figure.output.png,
